<a href="https://colab.research.google.com/github/ariefpurnamamuharram/MyTransformerResearch/blob/master/Deep_Learning_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning with PyTorch
____
YouTube videos:
- https://www.youtube.com/watch?v=c36lUUr864M

Basics of Tensor:
- torch.add(x,y) --> Addition of x and y
- torch.mul(x,y) --> Multiplication of x and y
- torch.rand(n)
- torch.sub(x,y) --> Substraction of x and y
- torch.view(1) --> Reshaping Torch Tensor

GPU functions:
- torch.cuda.is_available() --> Check if CUDA is available

In [29]:
# Install the required packages
!pip install torch torchvision torchaudio

In [33]:
# Basics of Tensor
import torch
import numpy as np

if torch.cuda.is_available(): # Check if CUDA is available
  device = torch.device("cuda") # Select CUDA device (ex: "CUDA:0")
  x = torch.ones(5, device=device) # Move Tensor to the GPU
  y = torch.ones(5)
  y = y.to(device) # Move Tensor to the GPU
  z = x + y # Processed at the GPU level
  # z.numppy(), will produce an error. NumPy only can be processed at CPU level
  z = z.to("CPU") # Move the Tensor to the CPU

In [58]:
# Autograd
# Gradient (Grad) is important in our model optimization

import torch

x = torch.rand(3, requires_grad=True) # By default is False
print(x)

y = x+2
print(y)
z = y*y*2
#z = z.mean()
print(z)

v = torch.tensor([0.1, 1.0, 0.01], dtype=torch.float32)
z.backward(v) # dz/dx, Jacobian products
print(x.grad)

# ----
# Stop PyTorch treating the gradient functions and tracking history in 
# our compational graphs.
# x.requires_grad_(False)
# x.detach()
# with torch.no_grad()

a = torch.rand(3, requires_grad=True) # By default is False
print(a)

a.requires_grad_(False)
print(a)

# ---

weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  model_output = (weights*3).sum()

  model_output.backward()

  print(weights.grad)

  # Clear it before the next epoch so the grad value is still right.
  weights.grad.zero_()

tensor([0.3010, 0.5801, 0.3912], requires_grad=True)
tensor([2.3010, 2.5801, 2.3912], grad_fn=<AddBackward0>)
tensor([10.5891, 13.3141, 11.4357], grad_fn=<MulBackward0>)
tensor([ 0.9204, 10.3205,  0.0956])
tensor([0.2824, 0.7041, 0.6977], requires_grad=True)
tensor([0.2824, 0.7041, 0.6977])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
