<a href="https://colab.research.google.com/github/ariefpurnamamuharram/MyTransformerResearch/blob/master/Deep_Learning_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning with PyTorch
____
YouTube videos:
- https://www.youtube.com/watch?v=c36lUUr864M

In [29]:
# Install the required packages
!pip install torch torchvision torchaudio

In [20]:
import torch

x = torch.rand(4,4)

y = x.view(-1, 8)
print(y.size())

torch.Size([2, 8])


In [24]:
# Tensor to NumPy
# Hati-hati jika dijalankan bersamaan di CPU, pointer yang akan diganti bersamaan
import torch
import numpy as np

a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [28]:
import torch
import numpy as np

a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
import torch
import numpy as np

if torch.cuda.is_available():
  device = torch.device("cuda")

torch.add(x,y)
torch.sub(x,y)
torch.mul(x,y)
torch.rand()
torch.view(1) --> Reshaping dengan *tensor*
torch.view(-1, matrix)